import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = (name) => readFileSync(path.join(root, name), 'utf8');
const config = JSON.parse(read('src-tauri/tauri.conf.json'));
const pkg = JSON.parse(read('package.json'));
const lock = JSON.parse(read('package-lock.json'));
const cargo = read('src-tauri/Cargo.toml').match(/^version\s*=\s*"([^"]+)"/m)?.[1];
const cargoLock = read('src-tauri/Cargo.lock').match(/name = "converter"\r?\nversion = "([^"]+)"/)?.[1];
if (![pkg.version, lock.version, lock.packages[''].version, cargo, cargoLock].every((value) => value === config.version)) {
  throw new Error('Versions must match in package.json, package-lock.json, Cargo.toml, Cargo.lock and tauri.conf.json.');
}
if (!/^\d+\.\d+\.\d+$/.test(config.version)) throw new Error('This release workflow publishes stable versions only.');
if (process.env.GITHUB_REF_TYPE === 'tag' && process.env.GITHUB_REF_NAME !== `v${config.version}`) {
  throw new Error(`Release tag must be v${config.version}.`);
}
const publicKey = read('src-tauri/updater.key.pub').trim();
if (config.plugins.updater.pubkey !== publicKey) throw new Error('Embedded updater key does not match updater.key.pub.');
const packet = Buffer.from(Buffer.from(publicKey, 'base64').toString('utf8').trim().split(/\r?\n/)[1] ?? '', 'base64');
if (packet.length !== 42 || packet.subarray(0, 2).toString() !== 'Ed') throw new Error('Expected a public key generated by the Tauri signer.');
const repo = process.env.GITHUB_REPOSITORY || 'leeisfailing/Converter';
if (!config.plugins.updater.endpoints.includes(`https://github.com/${repo}/releases/latest/download/latest.json`)) {
  throw new Error('The updater endpoint must point to this release repository.');
}
if (config.bundle.createUpdaterArtifacts !== true) throw new Error('Updater artifacts must be enabled.');
for (const binary of config.bundle.externalBin) {
  const filename = `src-tauri/${binary}-x86_64-pc-windows-msvc.exe`;
  if (!existsSync(path.join(root, filename))) throw new Error(`Missing Windows sidecar: ${filename}`);
}
if (!existsSync(path.join(root, 'src-tauri/bin/plugins/LSMASHSource.dll'))) throw new Error('Missing bundled LSMASHSource.dll. Include it when committing release resources.');
const trackedSecrets = execFileSync('git', ['ls-files', '--', 'src-tauri/updater.key', 'src-tauri/updater.key.password', 'src-tauri/private_key.pem', 'src-tauri/private_key_hex.txt'], { cwd: root, encoding: 'utf8' }).trim();
if (trackedSecrets) throw new Error('Private signing material must never be tracked by Git.');
console.log(`Release configuration validated for Converter v${config.version} (Windows x64).`);
